#!/usr/bin/env python3
import json
import re
import sys

from tones import tone_diacritic_to_number


def main():
    if len(sys.argv) < 2:
        sys.exit('Usage: json_to_txt FILE ...')
    for arg in sys.argv[1:]:
        with open(arg) as f:
            convert_dictionary(json.load(f))


bold_on = '\uEABE'
bold_off = '\uEABF'

link_on = '\uEAB8'
link_off = '\uEABB'

newline  = '\uEAB1'
double_newline = newline + ' ' + newline


def convert_dictionary(dictionary):
    for entry in dictionary:
        headword = entry['title']

        for heteronym in entry['heteronyms']:
            pinyin = '@' + tone_diacritic_to_number(heteronym['trs'])
            definitions = [d for d in heteronym['definitions']
                           if d['def'] not in {'', '綴\u20DE', '狀\u20DE'}]
            split_definition = []

            for i, defdict in enumerate(definitions):
                split_definition.append('')
                definition = defdict['def']

                if definition == '辨\u20DE&nbsp似\u20DE':
                    assert i+2 == len(definitions)
                    split_definition[-1] += bold_on + '辨似' + bold_off + '  '
                    split_definition[-1] += tone_diacritic_to_number(definitions[i+1]['def'])
                    break

                if len(definitions) > 1:
                    split_definition[-1] += bold_on + str(i+1) + bold_off + '  '
                if pos := defdict.get('type'):
                    split_definition[-1] += bold_on + pos + bold_off + '  '

                split_definition[-1] += tone_diacritic_to_number(definition)

                if examples := defdict.get('example'):
                    for i, example in enumerate(examples):
                        example = re.sub('[\uFFF9\uFFFA\uFFFB]', newline, example)
                        split_definition.append(tone_diacritic_to_number(example))

            if synonyms := heteronym.get('synonyms'):
                synonyms = link_on + (link_off + ' ' + link_on).join(synonyms.split(',')) + link_off
                split_definition.append(bold_on + '似' + bold_off + '  '  + synonyms)

            if reading := heteronym.get('reading'):
                split_definition.append('〈' + bold_on + reading + bold_off + '〉')

            definition = double_newline.join(d.strip(newline+' '+'\t'+'\n') for d in split_definition)
            print(headword, pinyin, definition, sep='\t')


if __name__ == '__main__':
    main()
