#!/usr/bin/env python3
import csv
from collections import defaultdict


def main():
    id_to_chinese = defaultdict(list)
    with open('moedict-data-twblg/uni/對應華語.csv') as f:
        #skip header
        next(f)
        csvreader = csv.reader(f)
        for row in csvreader:
            assert len(row) == 3
            id_to_chinese[row[1]].append(row[2])

    id_to_entry = {}
    with open('moedict-data-twblg/uni/詞目總檔.csv') as f:
        #skip header
        next(f)
        csvreader = csv.reader(f)
        for row in csvreader:
            assert len(row) == 6
            if int(row[1]) in range(11, 23):
                assert row[0] not in id_to_entry
                id_to_entry[row[0]] = row[2], row[3], row[1]

    with open('moedict-data-twblg/uni/釋義.csv') as f:
        #skip header
        next(f)
        csvreader = csv.reader(f)
        for row in csvreader:
            assert len(row) == 5
            if row[1] in id_to_entry:
                entry = id_to_entry[row[1]]
                if entry[2] == '12':
                    for chinese in id_to_chinese[row[1]]:
                        print(chinese, '@' + entry[0], row[4], sep='\t')
                else:
                    print(entry[0], '@' + entry[1], row[4], sep='\t')

if __name__ == '__main__':
    main()
